### ISSUE TITLE
openCommandOutputStream not working, bugfix included

### ISSUE THREAD

**Issue by yadaysw** [burdoto/VBAN-API#10]
Dont works the method:
VBAN.openCommandOutputStream(address,port).sendData(text)

Bug caused by missing initialization in **VBANPacket** one parameter constructor.

bugfix: just add one line to the end of constructor

    private VBANPacket(VBANPacketHead<T> head) {
        this.head = head;
        this.unfinishedByteArray = new UnfinishedByteArray(MAX_SIZE, true);

	unfinishedByteArray.append(head.getBytes());  // appended line
    }

**Comment by burdoto** [comment]
Stupid bug, apologies for this. I'll fix this as soon as I am back home, or if you could open a PR, I can already merge it and draft a release later.

**Comment by yadaysw** [comment]
sorry, github is not my home, this way is faster

**Comment by burdoto** [comment]
Alright. You can expect the new release on JitPack in ~6 hours and on Maven 1 day after that.

**Comment by yadaysw** [comment]
Thanx, nothing urgent, i just playing with it. (my local version works OK)

**Comment by burdoto** [comment]
The library has been updated and published and is now available [on GitHub](https://github.com/burdoto/VBAN-API/releases/latest) and [on JitPack](https://jitpack.io/#burdoto/VBAN-API/1.0.1).
The MavenCentral release should be available within the next 18 hours.

Thanks for reporting this bug!
